// サンプル暗号文データ
// アメリカ独立宣言を基にした500-1000文字の各種暗号サンプル

/*
* 平文（アメリカ独立宣言冒頭部分）:
* WHEN IN THE COURSE OF HUMAN EVENTS IT BECOMES NECESSARY FOR ONE PEOPLE TO DISSOLVE THE POLITICAL BANDS 
* WHICH HAVE CONNECTED THEM WITH ANOTHER AND TO ASSUME AMONG THE POWERS OF THE EARTH THE SEPARATE AND 
* EQUAL STATION TO WHICH THE LAWS OF NATURE AND OF NATURES GOD ENTITLE THEM A DECENT RESPECT TO THE 
* OPINIONS OF MANKIND REQUIRES THAT THEY SHOULD DECLARE THE CAUSES WHICH IMPEL THEM TO THE SEPARATION 
* WE HOLD THESE TRUTHS TO BE SELF EVIDENT THAT ALL MEN ARE CREATED EQUAL THAT THEY ARE ENDOWED BY THEIR 
* CREATOR WITH CERTAIN UNALIENABLE RIGHTS THAT AMONG THESE ARE LIFE LIBERTY AND THE PURSUIT OF HAPPINESS 
* THAT TO SECURE THESE RIGHTS GOVERNMENTS ARE INSTITUTED AMONG MEN DERIVING THEIR JUST POWERS FROM THE 
* CONSENT OF THE GOVERNED
*
* 各暗号サンプルは上記の平文（英字のみ、スペース除去）を各種暗号方式で暗号化したものです。
*/

export const CIPHER_SAMPLES = [
  {
    id: 'caesar',
    name: 'シーザー暗号 (Caesar Cipher)',
    description: '各文字を固定数シフトするもっとも基本的な暗号。',
    shift: 3,
    ciphertext: `ZKHQ LQ WKH FRXUVH RI KXPDQ HYHQWV LW EHFRPHV QHFHVVDUB IRU RQH SHRSOH WR GLVVROYH WKH SROLWLFDO EDQGV ZKLFK KDYH FRQQHFWHG WKHP ZLWK DQRWKHU DQG WR DVVXPH DPRQJ WKH SRZHUV RI WKH HDUWK WKH VHSDUDWH DQG HTXDO VWDWLRQ WR ZKLFK WKH ODZV RI QDWXUH DQG RI QDWXUHV JRG HQWLWOH WKHP D GHFHQW UHVSHFW WR WKH RSLQLRQV RI PDQNLQG UHTXLUHV WKDW WKHB VKRXOG GHFODUH WKH FDXVHV ZKLFK LPSHO WKHP WR WKH VHSDUDWLRQ ZH KROG WKHVH WUXWKV WR EH VHOI HYLGHQW WKDW DOO PHQ DUH FUHDWHG HTXDO WKDW WKHB DUH HQGRZHG EB WKHLU FUHDWRU ZLWK FHUWDLQ XQDOLHQDEOH ULJKWV WKDW DPRQJ WKHVH DUH OLIH OLEHUWB DQG WKH SXUVXLW RI KDSSLQHVV WKDW WR VHFXUH WKHVH ULJKWV JRYHUQPHQWV DUH LQVWLWXWHG DPRQJ PHQ GHULYLQJ WKHLU MXVW SRZHUV IURP WKH FRQVHQW RI WKH JRYHUQHG`
  },
  {
    id: 'affine',
    name: 'アフィン暗号 (Affine Cipher)',
    description: '文字を数式 y=(ax+b) mod 26 で変換する暗号。',
    a: 5,
    b: 8,
    ciphertext: `ORCVWVZRCSAEPUCAHREQIVCJCVZUWZNCSAQCUVCSCUUIPYHAPAVCFCAFLCZAXWUUALJCZRCFALWZWSILNIVXUORWSRRIJCSAVVCSZCXZRCQOWZRIVAZRCPIVXZAIUUEQCIQAVMZRCFAOCPUAHZRCCIPZRZRCUCFIPIZCIVXCKEILUZIZWAVZAORWSRZRCLIOUAHVIZEPCIVXAHVIZEPCUMAXCVZWZLCZRCQIXCSCVZPCUFCSZZAZRCAFWVWAVUAHQIVGWVXPCKEWPCUZRIZZRCYURAELXXCSLIPCZRCSIEUCUORWSRWQFCLZRCQZAZRCUCFIPIZWAVOCRALXZRCUCZPEZRUZANCUCLHCJWXCVZZRIZILLQCVIPCSPCIZCXCKEILZRIZZRCYIPCCVXAOCXNYZRCWPSPCIZAPOWZRSCPZIWVEVILWCVINLCPWMRZUZRIZIQAVMZRCUCIPCLWHCLWNCPZYIVXZRCFEPUEWZAHRIFFWVCUUZRIZZAUCSEPCZRCUCPWMRZUMAJCPVQCVZUIPCWVUZWZEZCXIQAVMQCVXCPWJWVMZRCWPBEUZFAOCPUHPAQZRCSAVUCVZAHZRCMAJCPVCX`
  },
  {
    id: 'playfair',
    name: 'プレイフェア暗号 (Playfair Cipher)',
    description: '2文字ずつ5×5の表で変換する暗号。第一次世界大戦で使用された。',
    key: 'MONARCHY',
    ciphertext: `XAFSBSDQFREKDGVLZFHXNBPQFOBUVLRQKLNQFOLMCNFUDQLDNQFEQDOKDRFTFGQLUOQVFQFLNQVHKQDLQQKDUQCZQFZGVLHKZQDZQRBQLQGHSDIDMLQFKBFCNQRQFSQCOQFNFQFPUHQDLCUKQSDQOKQLQKAQSLQZMIDNQHLZRQFLNQOHYVQKOLFRQCUKQCOFGXATQLQDQHCLFADQVQBLCDQKLDNQLQADQPQKSDQVFQFRQHGYVQBKQOMSDQFDZQHQDCFQRQFKLZQHMFQRZQNQLMXVFQNCRQFGBKDQFUFQDSQFLNQHCNFGLCXDORLNBQCMQFLNQGLKRBFGVQUQFSFQVQOYFQVSQBMFBQSLZDQGQCDQKQXDQBSDXFBMDQCZQLZZKNQCBQDKQCRQFQHYVLBZQRCDFGNBKQBQOUZQHQDWSFQZSQKFLXQOQBZQCRZQPZMFBLNBSQKQCQBQKDSFQBKBZQHDBQZSQKDKDNZQDQRQFQLHNQDQKSLGVFQPQBHKQFGDQCKDMHQDQZSDQCDQVQKSRQQDQDSBLNXQAMZHZUFQKQRCNFKGRLQKQEDQFSZYQVSNQODLBZQEQCRQXUHZQCDCQRSFQDZXYBSQFQVBKQHQKCMFZQNQDRFQFHBQVFBQFQKQEZSFQDQBQRQCQEDKXFZQBSQXQFDSDQKFQDLBGXOCDQQLFDQELZSFQLHXDBFHSZBZVQFDQEKBRGQKQLFLZZQDLBYSBSFQLQHFGQLQRSFGFCZQKQBYGFLVSLXOCDQXFBTDQEHVBQUQLSFQFOQCLQKSFQQLSOQSZYFQRQLFRQRKQCQFSFQEFOLQQFQRQLQEZQLKKQQH`
  },
  {
    id: 'railfence',
    name: 'レールフェンス暗号 (Rail Fence Cipher)',
    description: '文字をジグザグ状に配置して読み取る転置式暗号。',
    rails: 3,
    ciphertext: `WEIECUSOHMNEETSTOESNEESRFROEPETDSOLETHPLTCLADSHIHAEOECETVTHAEERSOFTERDNATSMOGTEEOWROTESPATADQUSTAOHCTEASM OLHSTUHSTELEIETNHTALMENRCREAEEULTA HYROEDBITRATEWHCINLNBEGTWATTMOGTET  SREIQLTIDMTESPRT SAOATHHPPOHE EHEEAENNUEVSTEUFHRTSAOHESRRTTGVRMNSI DRNTEIJSPWRMH NTOHEOEEH NNHUE HNAATEEDDOSREQESAYHGMNTOSOPOINOMNINRQIETTYPELDECAHCASWIHLIPEIHSWAOQINATONESRFEQTFNHRSESRGRTAENMNGTSSEMIHVNBSUTL IHNEQHWDSEQPRHGLQFBIFSGQWMGVAHHLAUFTEEIVHIHTTLMENAEDQAATYARRTEELAIEHTTLRDKIGAOTTSECNHUNIAAEIHWHSRVCOTEETOHOEGEOGAIYTFRFNHNNMOETSCRHLEIETNDLGVHHQNEFDTHSHEOAROTGOIOMNKHDDIHCOIEITHEQDTGMPETVWENRETRHE`
  },
  {
    id: 'columnar',
    name: '完全縦列転置式暗号 (Columnar Transposition)',
    description: '文字を列状に配置してキーワード順に読み取る転置式暗号。',
    key: 'ZEBRAS',
    ciphertext: `HEOEUEEVNTBESLTIFHEEAEORAGOTNOESFMSMNUSECRSIESUEHTUTEQLHVADRQEEGREEITEAIHDEOLSTLVNIRTTIDMSIGAEBRETQEALRPATEHTEHGHTSLEETUAMOIHEIORAESRTSOSFRMEOREDSTIHTINTEISTNEOEHEGHMHRIINAHOATWHTMAREOECEESTGRNSDUTEPMEWAHVTSATDNHHEAOLREREISAOQLNSREEUTINPHTASADTEEQHOPNNEOOAFUASARLTCEHRCUDHPGTNUNSOEIWHRGLIMIATTMAETOHIPFRIEEWOMHIOEATNYIEEOTHDAOOSVRQOSSOAOHTNPTEIESUTSUEAEAFOHFNLEEHRHQTELRAEEOEVTGIWEITTAERQRHIWUULHRIEEEATMETEREBTLLCTEIMEMVQEFGOLRVEWSTOTEATITQELENTNNWAFMRFUAAHRRTAATNHEAEPTIMDGBAFIETLDFEVGOTEWTTOELRNHEPRHTAEREHDRSUSEHTORLHTRHLHTLTRRMEVEHQRGEQHMTSEHTEEHNISDETRETRLERTGONOIETNERTGTUOTTHVNRMTMHQMRIVOOUADNRAOMHFPEEEFOAIEHHONRIMUTRVSEVTOOCEEEVLOTRNRTUOIATHRRVNQTEREEDFENEFGOGETLRSSATMSIAEEUVEENINIGFHTOWHQOHOEPRPEGWHPEAOETVTOEUARAEAIRTDGETHNCFRNRTSEIURMMNEETATTTCORHOMULGEOLNNEATESUHHRTFAEEFSTIRGNEUDOOEVMTNMNUEOAAEAITSEGLTGSEHRMYALMLEENORHOWDRRGOITTETFOHRAAEHTTEPOQIGDOTNNDHSRMGSOVWFQRNWTRHNIUTMHTOOHTNHTMFEVENHNOERIETVRM`
  },
  {
    id: 'grille',
    name: '回転グリル暗号 (Rotating Grille)',
    description: '正方形の格子を回転させながら文字を配置する暗号。',
    gridSize: 8,
    ciphertext: `WNHETIEORPNHCEUFEOSUEQHVFNRATUBMSMAEECNCRTYEHNTONTHIIVABNTTMHSNWEEQEEEHLHUETVOFHRHMANTQESRLNFAEENCCEMLOIORVHHPETEENRRSHEAEITREYMLSETIPUMHSLLGOTASDTEEOEEMSDIRWCATTABEONEREHOAENSUNAHDAOEETNSTIEHNAEPRHISRAIETTSTLSLMEQHATERESQERAEWHEETOQVEFNHSAIVOWERTMHNHAFLORETRRDEQTEHBHEUYTEEQHEHQOUETEOATOAEVEUISGLSNEATETTETDLFQTLNEOEEGQNILTIEMTQNAHHAEITTOOATHRERHTSATSEERNSEQWFNNOHTTEQTEATRLIIRTTMHQRPETNHTQELUFOEHEEIMEMTIVHIETEHAAAVEIUTVEITTSTHSEEOTSTRTREEAELCROQAMHODDLTAQPTHVMNSLEGEHOEHIFPRFNRVEEEENTQEROHGTRNVDRMTSAETDITTAUHHOSOMRDSNMRUSFVLHEPRVSFNIUOCVLEETRTOENIETUAERUOIEUNETOTDVROQNERETRFREMTTDGNOEREHTQURHMNHTOEANPNNFHRSRUGNNRFOOEHQTYEVIVESQSIEQIAEFDLEESETAAECEATNRRLTOSEERUHHSUDNREMOEELAYHHLEEURHQTTHOQOHNETLVTVITQAEEREETTQRHDEITNLGGHTEQFADMQEIEANRTSEQRTPEDTORNOOEFEIEDSEEMDVEIMTTQNHSQUATVOHTHNOLQWDEAENAGFHRTUHTFVGEORTVLNEOGAEERITQQTRQUDNAOHAERVURCEMNFEENOAGTQRMQHQTMGDEEEHFIAHVLOPEPRTSTTHAERNIMQTHIAEGTOEIHEEQ`
  },
  {
    id: 'vigenere',
    name: 'ヴィジュネル暗号 (Vigenère Cipher)',
    description: 'キーワードを繰り返し使用して各文字を異なる量シフトする多表式暗号。',
    key: 'INDEPENDENCE',
    keyLength: 12,
    ciphertext: `EUHRXRGKIPQYZFHSULHPEAGZMAWWXXOHGBOIAAHGTWFDVLHSZBQIEIBSPRVSLVVWDPIHXUGTWYLXXGNOFNPHAJKMRLUDZRESVAHGIIQWLROAQGKECSGKIECRLGREHWHPINOSVTWLTTBZIEUSNGKITEEWLFGTIEDXTEAGIDWETFWEIMBQXBYLQPKXWIYDAFQJVNWYGINQHBHRIGXVTWTRHRPXQGOIILRPEQGGMAWVTWCHGGVSBUHSEMALSAUSNZDRZMAGVRSYQEHWILNWXUGCAURYAHQHGYCVMGKIREHVIFYLQPKMBTROXUGQBBWLTWRSEECXQBQATLBOHGJIARWVJXUVXBDIAROJTZVGIAVXPNWEAPZHRNTIKEHEIIQHUHCPBUDXILRBEEGIVQRATHOBXUGMZPUIPXBUGRTXIVQYCEYLIACFTRUMVLGVXUCXIZRRVXUHWRCVMYLJTPVEIEVCIAGXWICXVFWMBBILPTCLRRUWBUDXISNOPZGROBYIGRZHRGUEZRLRHXVWYGGHIZRRVQRQHRTMDVQKILRLVWWWBCRATVFIVBOXPRFSCWRQXBHXPRJSKIEQIQVLIGZLTRRYIECRGSRVBSSJSIGVVZHRIFRFSZGWLRVXGYPWMIGSNGKIHIRQHFKXQFWLTVVJLGQJBUHTTSCOIGQETGHVDVGDFBNMAULXPRQWSVPWBVWYIIAHATQZMEQQTRGOELKROVWWUSHQHNVMWARRHYPKTEKRKVSPTWNQHBTKIALDXRTLXFRSERUWXRFXGUHSZZDWISGKIZULIYOEETRDVZQWBYLOTPLWSRHJMPWXWIVUWNHIBLDRSTYHEFWVMCUYSIAFIVPHMRGAXPYGMPVEBR`
  },
  {
    id: 'vigenere2',
    name: 'ヴィジュネル暗号2 (Vigenère Cipher - 短い鍵)',
    description: '短い鍵（5文字）を使用したヴィジュネル暗号。周期性がより明確に現れる。',
    key: 'EAGLE',
    keyLength: 5,
    ciphertext: `AHKYMRTNPGSUXDISFNFQENKGIRTYTXFEIZQISTPGISYLVCFUCSREVPSTLKESHIYDSPVKELIPUWMXIILPFATOWAHONLLABPGSNTPGXEJELIMCTXLATZXLEXLRHTULWWUSPEQOTRXLEVZAIRYZJXHKPEVTNDITAXLXIATOIUUGWWXAZTSRTUHLMCNELILGHWSFTLXYRKLRHOLYEXUXPWKOJPRXIZWIXHKXEHEIPRXRKDTICZESXHKZTMNOZRWOLXERKOYHVEWFMVEYELETZSICSNZYPDJPGPAXPXLEILYWEYHLMCNTQTERELIMZZXLEYPTERGEMSNCPLSLJELISKEVYTNDXSBKDIPFKGMHETEXLAZLPPMKYEVEICIETKOIUUGWXLAZELIYGCIINJZAIDHJXLEOCGVEGESVCKCXEITFRELOPREBRPVMGNEWXHGEEQOTRXLEYPEVERTJILOMIVTELRHTNPTYRYFMXOLSETPOYIWSZSEXTULPPMKYKSVKCRQETEWERKTRWTOEYXEJLQSNMXIRDKCMZITRXLEOCNYSZASAEXDJVOSELICUYWINZZJXHKRSZEXYIHTNLXAHKYIZEXLRCFUCQSFMZZIRTXIRTHPGSMKDHISZCYGTOGISFZSIWEKYHWIZTWXHKCMKHZZJXHKAISPRPXSAREIVOXEEFORTWLIZLRHTUTRWTOEYXETPAKOBPVRMKYXPAETRKIZDJSUTOEXIUYSRSANLTROYGMPRPWENJZVKATTDMNMTXWPUHIVSOYWYCNQSVMGDXSTNPQWHGWPEPVPEVMUDXPIQPPCTUPJJEIEXLEOCWEFKECENJAPIAYFVIPXFHINIPMRDKPHAIRWHMCZLXI`
  }
];