// サンプル暗号文（tools/build-samples.mjs が生成。手で編集しない）
// 平文はアメリカ独立宣言（1776年）の冒頭の英字。米国でパブリックドメイン。
// 暗号文は js/cipher-core.js の参照実装で作った（5文字ずつ区切っている）。名前と説明は messages.js にある。

export const SAMPLE_PLAINTEXT = [
  'WHENINTHECOURSEOFHUMANEVENTSITBECOMESNECESSARYFORONEPEOPLETODISSOLVETHEPOLITICALBANDSWHICHHAVECONNEC',
  'TEDTHEMWITHANOTHERANDTOASSUMEAMONGTHEPOWERSOFTHEEARTHTHESEPARATEANDEQUALSTATIONTOWHICHTHELAWSOFNATUR',
  'EANDOFNATURESGODENTITLETHEMADECENTRESPECTTOTHEOPINIONSOFMANKINDREQUIRESTHATTHEYSHOULDDECLARETHECAUSE',
  'SWHICHIMPELTHEMTOTHESEPARATIONWEHOLDTHESETRUTHSTOBESELFEVIDENTTHATALLMENARECREATEDEQUALTHATTHEYAREEN',
  'DOWEDBYTHEIRCREATORWITHCERTAINUNALIENABLERIGHTSTHATAMONGTHESEARELIFELIBERTYANDTHEPURSUITOFHAPPINESST',
  'HATTOSECURETHESERIGHTSGOVERNMENTSAREINSTITUTEDAMONGMENDERIVINGTHEIRJUSTPOWERSFROMTHECONSENTOFTHEGOVE',
  'RNED'
].join('');

export const CIPHER_SAMPLES = [
  {
    id: 'plain',
    type: 'plain',
    params: {},
    ciphertext: `WHENI NTHEC OURSE OFHUM ANEVE NTSIT BECOM ESNEC ESSAR YFORO NEPEO PLETO DISSO LVETH EPOLI TICAL BANDS WHICH HAVEC ONNEC
      TEDTH EMWIT HANOT HERAN DTOAS SUMEA MONGT HEPOW ERSOF THEEA RTHTH ESEPA RATEA NDEQU ALSTA TIONT OWHIC HTHEL AWSOF NATUR
      EANDO FNATU RESGO DENTI TLETH EMADE CENTR ESPEC TTOTH EOPIN IONSO FMANK INDRE QUIRE STHAT THEYS HOULD DECLA RETHE CAUSE
      SWHIC HIMPE LTHEM TOTHE SEPAR ATION WEHOL DTHES ETRUT HSTOB ESELF EVIDE NTTHA TALLM ENARE CREAT EDEQU ALTHA TTHEY AREEN
      DOWED BYTHE IRCRE ATORW ITHCE RTAIN UNALI ENABL ERIGH TSTHA TAMON GTHES EAREL IFELI BERTY ANDTH EPURS UITOF HAPPI NESST
      HATTO SECUR ETHES ERIGH TSGOV ERNME NTSAR EINST ITUTE DAMON GMEND ERIVI NGTHE IRJUS TPOWE RSFRO MTHEC ONSEN TOFTH EGOVE
      RNED`
  },
  {
    id: 'caesar',
    type: 'caesar',
    params: { shift: 3 },
    ciphertext: `ZKHQL QWKHF RXUVH RIKXP DQHYH QWVLW EHFRP HVQHF HVVDU BIRUR QHSHR SOHWR GLVVR OYHWK HSROL WLFDO EDQGV ZKLFK KDYHF RQQHF
      WHGWK HPZLW KDQRW KHUDQ GWRDV VXPHD PRQJW KHSRZ HUVRI WKHHD UWKWK HVHSD UDWHD QGHTX DOVWD WLRQW RZKLF KWKHO DZVRI QDWXU
      HDQGR IQDWX UHVJR GHQWL WOHWK HPDGH FHQWU HVSHF WWRWK HRSLQ LRQVR IPDQN LQGUH TXLUH VWKDW WKHBV KRXOG GHFOD UHWKH FDXVH
      VZKLF KLPSH OWKHP WRWKH VHSDU DWLRQ ZHKRO GWKHV HWUXW KVWRE HVHOI HYLGH QWWKD WDOOP HQDUH FUHDW HGHTX DOWKD WWKHB DUHHQ
      GRZHG EBWKH LUFUH DWRUZ LWKFH UWDLQ XQDOL HQDEO HULJK WVWKD WDPRQ JWKHV HDUHO LIHOL EHUWB DQGWK HSXUV XLWRI KDSSL QHVVW
      KDWWR VHFXU HWKHV HULJK WVJRY HUQPH QWVDU HLQVW LWXWH GDPRQ JPHQG HULYL QJWKH LUMXV WSRZH UVIUR PWKHF RQVHQ WRIWK HJRYH
      UQHG`
  },
  {
    id: 'caesarShort',
    type: 'caesar',
    params: { shift: 7 },
    ciphertext: `DOLUP UAOLJ VBYZL VMOBT HULCL UAZPA`
  },
  {
    id: 'affine',
    type: 'affine',
    params: { a: 5, b: 8 },
    ciphertext: `ORCVW VZRCS AEPUC AHREQ IVCJC VZUWZ NCSAQ CUVCS CUUIP YHAPA VCFCA FLCZA XWUUA LJCZR CFALW ZWSIL NIVXU ORWSR RIJCS AVVCS
      ZCXZR CQOWZ RIVAZ RCPIV XZAIU UEQCI QAVMZ RCFAO CPUAH ZRCCI PZRZR CUCFI PIZCI VXCKE ILUZI ZWAVZ AORWS RZRCL IOUAH VIZEP
      CIVXA HVIZE PCUMA XCVZW ZLCZR CQIXC SCVZP CUFCS ZZAZR CAFWV WAVUA HQIVG WVXPC KEWPC UZRIZ ZRCYU RAELX XCSLI PCZRC SIEUC
      UORWS RWQFC LZRCQ ZAZRC UCFIP IZWAV OCRAL XZRCU CZPEZ RUZAN CUCLH CJWXC VZZRI ZILLQ CVIPC SPCIZ CXCKE ILZRI ZZRCY IPCCV
      XAOCX NYZRC WPSPC IZAPO WZRSC PZIWV EVILW CVINL CPWMR ZUZRI ZIQAV MZRCU CIPCL WHCLW NCPZY IVXZR CFEPU EWZAH RIFFW VCUUZ
      RIZZA UCSEP CZRCU CPWMR ZUMAJ CPVQC VZUIP CWVUZ WZEZC XIQAV MQCVX CPWJW VMZRC WPBEU ZFAOC PUHPA QZRCS AVUCV ZAHZR CMAJC
      PVCX`
  },
  {
    id: 'substitution',
    type: 'substitution',
    params: { keyword: 'LIBERTY' },
    ciphertext: `VARJC JQARB KSOPR KTASH LJRUR JQPCQ IRBKH RPJRB RPPLO XTKOK JRMRK MGRQK ECPPK GURQA RMKGC QCBLG ILJEP VACBA ALURB KJJRB
      QREQA RHVCQ ALJKQ AROLJ EQKLP PSHRL HKJYQ ARMKV ROPKT QARRL OQAQA RPRML OLQRL JERNS LGPQL QCKJQ KVACB AQARG LVPKT JLQSO
      RLJEK TJLQS ORPYK ERJQC QGRQA RHLER BRJQO RPMRB QQKQA RKMCJ CKJPK THLJF CJEOR NSCOR PQALQ QARXP AKSGE ERBGL ORQAR BLSPR
      PVACB ACHMR GQARH QKQAR PRMLO LQCKJ VRAKG EQARP RQOSQ APQKI RPRGT RUCER JQQAL QLGGH RJLOR BORLQ RERNS LGQAL QQARX LORRJ
      EKVRE IXQAR COBOR LQKOV CQABR OQLCJ SJLGC RJLIG ROCYA QPQAL QLHKJ YQARP RLORG CTRGC IROQX LJEQA RMSOP SCQKT ALMMC JRPPQ
      ALQQK PRBSO RQARP ROCYA QPYKU ROJHR JQPLO RCJPQ CQSQR ELHKJ YHRJE ROCUC JYQAR CODSP QMKVR OPTOK HQARB KJPRJ QKTQA RYKUR
      OJRE`
  },
  {
    id: 'vigenere',
    type: 'vigenere',
    params: { keyword: 'INDEPENDENCE' },
    ciphertext: `EUHRX RGKIP QYZFH SULHP EAGZM AWWXX OHGBO IAAHG TWFDV LHSZB QIEIB SPRVS LVVWD PIHXU GTWYL XXGNO FNPHA JKMRL UDZRE SVAHG
      IIQWL ROAQG KECSG KIECR LGREH WHPIN OSVTW LTTBZ IEUSN GKITE EWLGJ IARSE GEGHE AFIYH DPHXN WMBPX WJKMR LGKIY CAABI RPXHU
      INPHW SQEIY EHWTQ HMAWM IPRWL ROELR FICXE HWCGG BGRXW IBSMA KSVFR JBEAN MAFVM DXMGI FWLNV XPRBW WSHOH QGGTN UIILR FEHUI
      AJKMR LVPTR NXPRP XDXUH WRREZ NWMDR JHLBN HBUHW TXEXX UUXWO HWTPS HZVFI VGWLP XNOPZ GRIEH GGINW IQGUC NOXWE GWLRA EZRHR
      SSJHH OAXPR LVRVR DXBTA QGKGT VGDMA WRIYL ICEOO IEKKP GVXWE GDQBP KBUHW TEEHP VHITV EIGXL DRQVL MCXVH YVWSS JEXCL RTWFW
      LNVXW FHGJV RWLRU IZVJL IWTRZ RTRUR QXHEE HMAUX QGXXT HNPSA IQMAG IGMIL RTVLM VUNJW GSSJG VASUS BXUHG BPWMA WSUXU HKBXI
      ZAHH`
  },
  {
    id: 'vigenereShort',
    type: 'vigenere',
    params: { keyword: 'EAGLE' },
    ciphertext: `AHKYM RTNPG SUXDI SFNFQ ENKGI RTYTX FEIZQ ISTPG ISYLV CFUCS REVPS TLKES HIYDS PVKEL IPUWM XIILP FATOW AHONL LABPG SNTPG
      XEJEL IMCTX LATZX LEXLR HTULW WUSPE QOTRX LEVZA IRYZJ XHKPE VTNEL ISKAE VAZPE RDKBY ELYEE XIUYX SWNTG LTNPP EWYZJ RAZFV
      IATOS JNGEY VEYRS HETEM XLKEL IMGOI GETEV ISVPG XTUEL IOVTR MOTDS JMGYO MNJCI UUOCI WTNLX XHKJW LOAWH HEIWE VEZSI GAADI
      WWNTG LISAI PTNPQ XOZSI WEVLV ETOZR AENZP HTNPW ITXFX LSZZF ISKWJ IVOOI RTZSE XARWQ INGCI GRKLX IDKBY ELZSE XTNPC ERKPR
      HOCPH FYZSI MRICI ETUCA MTNNI VTGTR YNGWM INGMP IRORL XSZSE XASZR KTNPW IAXPP MFKWM FEXEC ENJEL IPACW YIZZJ LAVAM REYDX
      LAZES WEIFV ITNPW IRORL XSMZZ IRTXI RTYLV IITDX MTAEI HASZR KMKYH IROGM RGZSI MRPFW XPUHI VSLCS QTNPG SNYPR XOLEL IGUGI
      VNKO`
  },
  {
    id: 'playfair',
    type: 'playfair',
    params: { keyword: 'MONARCHY' },
    ciphertext: `VYGMG APDLE MVATF MPFMC RAFUG MLTKS CIHMC LQALE ILXBN DPHMN MGLFH VULPR BKXAP APUKL CFVHS ESKBM SCRAB TVYEB BVBOU FHMAW
      MGDLK CPDLC XGPDR ARPCF MRRYP RBXLX CLRON AKQCF VHUGA THPPD IUIMD ZDPCF LISOM RLKRA CKLWM STLRS FARQN VBFHY PDLUN XPAGO
      RSZMI MRYHP ARLZM KQIRH GMSKL PKLCF ORCKE LRQMK TQLES ZPRPD FMSFA GNAPA EORAE KRYMK LWKAI LPDRS PDGCP BMVTC CKEUR MKLCF
      BMXLI LVYEB BFOLL UPDLC PRPDI LFLRM RSFAY NFCMP KZCFL IZDZL BPPRC ILIPE FUKBG MSZPD RSMSU CGMRM LEMKR SKCGL XMPLB OSZPD
      GCRMI UGMHR UGCDD QCFKA DMIMP RNZKS YHKMS RGAWM MSKFA RCSKM KIDPT LBOSR ONYQP DILIM MKSEG FSECI DZBNR YPDFL ZMLXK SHPBO
      SVSFM GXATL BOSZP RLIEM MKPDI LKMKI DPQIH OKMAO GMLTR MFKAQ SKLZL KBRON YQCLR YKMFX GAKQC FKAEX TLVHU GATKO NOPDL ENALI
      RQHPP DFIHO KMMGB Z`
  },
  {
    id: 'railfence',
    type: 'transposition',
    params: { rails: 3 },
    ciphertext: `WIERF AEICS ERRPL DOTOI BSCVN THINE DSENE EFEHS RAQSI OCESA EOTSE THDNS THINM IERHH HDLTA SCPHO SROHT ETOEV NALAR EUHHR
      DDHCT IEIAN EHHMT ELLRN ESOPE HOUHR TVMSI IEOER NEUOS MCEFG RHNNH CUSOH MNVNS TEOEN CSAYO OEEPE OISLE HPLTC LADWI HAEON
      CETEW TAOHR NTASM AOGHP WROTE ATTEE AAENE ULTTO TWIHH LWONT RADFA UEGDN ILTEA EETEP CTTEP NOSFA KNRQI ETATE SOLDC AEHCU
      EWIHM ETETT EEAAI NEODH STUHT BSLEI ETHTL MNRCE TDQAT ATEAE NOEBT ERRAO WTCRA NNLEA LRGTT AAOGH SAEIE IETAD HPRUT FAPNS
      TATSC RTEEI HSOEN ETAEN TTTDM NMNEI IGHIJ SPWRF OTEOS NOTEO ENDET OEUET BMESF NOTSV EIANH HCEDM HTAOU MTOSH RHPTD AANHT
      AFUNN ROTEM CREOO IONDU STYUE RESHI LMHPT WLERS EFDTA EEAEL TYEWY IERHT UIBIS TNERF BYTUI HISTE ESGGR NRSUA GDVTR TERHN
      THVE`
  },
  {
    id: 'columnar',
    type: 'transposition',
    params: { keyword: 'ZEBRAS' },
    ciphertext: `IOFEI MEFPT OEINC CTMNA SMESE HRDSN CAANT OTMNE HIMDR THETS CLOPO LESED AEREH YDYCR EUNIH NEFRT SHETU STRSS EGRTU EMNFV
      EEEAT CERNL STIBH VEHHE OETEH HPAAI HEFEN STHCS OIOIU HYDRA HPMST HETEV TLEEL HEDIT HIIES MELBN UOIHE HGVNI UODNR ORCTG
      EHHSM NENAO PIELL WANTT HTMGW TTEEU TWHOR FENTE ETPSK QTELA CWMEE AEHUB ETLRT ATEEE ATALL TAHEI APTPT STIOE ETMNI IPFEN
      ENNCO NSOCY EESHT AIECE ARAAH RETAN LOILN AAGIE EPTNF NIASD EUIET EIOSH SIHMC DTENB ROCNE RTOSI EDRFN ACEHE TNTNE GJWOO
      OODNU HVTES OEOLP CDHOE WONSO POAEA ETTHW TDUDL ATCEO ARETO CHEHT TANDT TLETN EQAAO TRWRN AGAGA ETHUA STRES NATDM IHSRT
      STEWT RUEBS SRODV OASHN DITDU NOFRS TQAOT SUORE EDRTO NNESH ULESI HHRWT ROFNA AAUTR WHEIT ABHTT RLYEI PSOER GMRIA EVETS
      HEHR`
  },
  {
    id: 'adfgvx',
    type: 'adfgvx',
    params: { square: 'INDEPC176ABFGHJKLMOQRSTUVWXYZ0234589', keyword: 'LIBERTY' },
    ciphertext: `FAAXG XADGX GXDXA GAFGG AADGV XVAAF FVGGA GFXGV GXAVA VGDGG AVAVD AGGGG AAGVA FAGAA GDGXA FAGGG GFFGA GFDAD GGDVV AFGGV
      GXAVG VDXGG FGAFA GGAAA GGADA VAVDX GGAXD VAGGV DAGGG XFGFA GGDAA VFAAA FGGVG FFAAX FGADA GGAFG GVGGA GGDGG AAGVG GADFA
      AXGXF AGFGX GVGFG GFGDV AXGAG AFGDV DAGGA VAGAD GXGAA GDAAA GVVAA VGXAD AGAAG GADFD GVGGA FGVFG GVGVG GAFAV GGGVG ADGFA
      GGGVA GAVVF AGGGA GGGGD GDGFA GAAAX FFVAA XGFGD ADGAG FDADG GGDAA AGAGD AAVAG AGAXD GAGGG AGGDA DDXFA AGDGG DAGAD GVGDG
      VGGAF DFGDF DAGAG GGADF GGXGG ADAXA GGDFV FVAVG DGVAX GGDAG GFDAG AGDDG DAGAF GAAGA ADFGD FAGFD AGDAF GDAGD AGVAA FGAGA
      VGGFD ADAFA GGVGG DGAGV DFAAD AGAGA GGGGV FAGAA VAVGA DXAGA AADAA GGFGA AAFFG DGGVG DFDFG DFADG AAVFG AFAVA AAXFF GGDDF
      VAFAX VXAVG DAGAD GGGGA VADDV AGDFD DFGAD VGGVA XDXAG GDFGF GGAAF ADGAF VGDGX GGFGA XGGGX DDAFA DFVAX GXAAA AAADA FDXVV
      DAAGG AAAGA FVGVF DFDAD GVVDG FGGAA FAGVD DGGAF DVGAA DVXGG DVGFA GFGGG GVAAG GAGGV GGGFD VDGAA FGGGG AAVAV FAAGA VDXGF
      ADGVV GGFFF DFFFA GAVFG GAFGF GAGGV GAADG VAFAF GAADG DGGGX AAGAG AGAAD GVGFG GXGXD AGVFD GFGGA VGVFA AVADF GAVFD DVDVG
      GADVG FGGGG GAGDA VXADA XAXGG AAGXA VAVFV GAADG FFVGX AGFGG AFVFV AFGGA GGDDG VGFGA FAGGV GGAAD DAGVD GDFDA AGVAD DVFGD
      VGXDV AVGGA GAVVD GFGVA AAGAV GGVGF GGVFA AAVGG FGAGA XAGVF AVGGV DFADF ADADA DAGFG GGDDA DGDGV AFDGF GADFG GDGDA XFGGV
      DXGVG DAADD ADADF GFGGD GGAXG XFGDA FFGFG VFAAD FGAGA XFVDG VVAXG DAVGV DGFVD DAGAV GGFXA XAGFV AGGAG AFVAG GFAGG AFFGD
      DXAGG DVD`
  }
];
