// サンプル暗号文（tools/build-samples.mjs が生成。手で編集しない）
// 平文はアメリカ独立宣言（1776年）の冒頭の英字。米国でパブリックドメイン。
// 暗号文は js/cipher-core.js の参照実装で作った（5文字ずつ区切っている）。名前と説明は messages.js にある。

export const SAMPLE_PLAINTEXT = [
  'WHENINTHECOURSEOFHUMANEVENTSITBECOMESNECESSARYFORONEPEOPLETODISSOLVETHEPOLITICALBANDSWHICHHAVECONNEC',
  'TEDTHEMWITHANOTHERANDTOASSUMEAMONGTHEPOWERSOFTHEEARTHTHESEPARATEANDEQUALSTATIONTOWHICHTHELAWSOFNATUR',
  'EANDOFNATURESGODENTITLETHEMADECENTRESPECTTOTHEOPINIONSOFMANKINDREQUIRESTHATTHEYSHOULDDECLARETHECAUSE',
  'SWHICHIMPELTHEMTOTHESEPARATIONWEHOLDTHESETRUTHSTOBESELFEVIDENTTHATALLMENARECREATEDEQUALTHATTHEYAREEN',
  'DOWEDBYTHEIRCREATORWITHCERTAINUNALIENABLERIGHTSTHATAMONGTHESEARELIFELIBERTYANDTHEPURSUITOFHAPPINESST',
  'HATTOSECURETHESERIGHTSGOVERNMENTSAREINSTITUTEDAMONGMENDERIVINGTHEIRJUSTPOWERSFROMTHECONSENTOFTHEGOVE',
  'RNED'
].join('');

export const CIPHER_SAMPLES = [
  {
    id: 'plain',
    type: 'plain',
    params: {},
    ciphertext: `WHENI NTHEC OURSE OFHUM ANEVE NTSIT BECOM ESNEC ESSAR YFORO NEPEO PLETO DISSO LVETH EPOLI TICAL BANDS WHICH HAVEC ONNEC
      TEDTH EMWIT HANOT HERAN DTOAS SUMEA MONGT HEPOW ERSOF THEEA RTHTH ESEPA RATEA NDEQU ALSTA TIONT OWHIC HTHEL AWSOF NATUR
      EANDO FNATU RESGO DENTI TLETH EMADE CENTR ESPEC TTOTH EOPIN IONSO FMANK INDRE QUIRE STHAT THEYS HOULD DECLA RETHE CAUSE
      SWHIC HIMPE LTHEM TOTHE SEPAR ATION WEHOL DTHES ETRUT HSTOB ESELF EVIDE NTTHA TALLM ENARE CREAT EDEQU ALTHA TTHEY AREEN
      DOWED BYTHE IRCRE ATORW ITHCE RTAIN UNALI ENABL ERIGH TSTHA TAMON GTHES EAREL IFELI BERTY ANDTH EPURS UITOF HAPPI NESST
      HATTO SECUR ETHES ERIGH TSGOV ERNME NTSAR EINST ITUTE DAMON GMEND ERIVI NGTHE IRJUS TPOWE RSFRO MTHEC ONSEN TOFTH EGOVE
      RNED`
  },
  {
    id: 'caesar',
    type: 'caesar',
    params: { shift: 3 },
    ciphertext: `ZKHQL QWKHF RXUVH RIKXP DQHYH QWVLW EHFRP HVQHF HVVDU BIRUR QHSHR SOHWR GLVVR OYHWK HSROL WLFDO EDQGV ZKLFK KDYHF RQQHF
      WHGWK HPZLW KDQRW KHUDQ GWRDV VXPHD PRQJW KHSRZ HUVRI WKHHD UWKWK HVHSD UDWHD QGHTX DOVWD WLRQW RZKLF KWKHO DZVRI QDWXU
      HDQGR IQDWX UHVJR GHQWL WOHWK HPDGH FHQWU HVSHF WWRWK HRSLQ LRQVR IPDQN LQGUH TXLUH VWKDW WKHBV KRXOG GHFOD UHWKH FDXVH
      VZKLF KLPSH OWKHP WRWKH VHSDU DWLRQ ZHKRO GWKHV HWUXW KVWRE HVHOI HYLGH QWWKD WDOOP HQDUH FUHDW HGHTX DOWKD WWKHB DUHHQ
      GRZHG EBWKH LUFUH DWRUZ LWKFH UWDLQ XQDOL HQDEO HULJK WVWKD WDPRQ JWKHV HDUHO LIHOL EHUWB DQGWK HSXUV XLWRI KDSSL QHVVW
      KDWWR VHFXU HWKHV HULJK WVJRY HUQPH QWVDU HLQVW LWXWH GDPRQ JPHQG HULYL QJWKH LUMXV WSRZH UVIUR PWKHF RQVHQ WRIWK HJRYH
      UQHG`
  },
  {
    id: 'caesarShort',
    type: 'caesar',
    params: { shift: 7 },
    ciphertext: `DOLUP UAOLJ VBYZL VMOBT HULCL UAZPA`
  },
  {
    id: 'affine',
    type: 'affine',
    params: { a: 5, b: 8 },
    ciphertext: `ORCVW VZRCS AEPUC AHREQ IVCJC VZUWZ NCSAQ CUVCS CUUIP YHAPA VCFCA FLCZA XWUUA LJCZR CFALW ZWSIL NIVXU ORWSR RIJCS AVVCS
      ZCXZR CQOWZ RIVAZ RCPIV XZAIU UEQCI QAVMZ RCFAO CPUAH ZRCCI PZRZR CUCFI PIZCI VXCKE ILUZI ZWAVZ AORWS RZRCL IOUAH VIZEP
      CIVXA HVIZE PCUMA XCVZW ZLCZR CQIXC SCVZP CUFCS ZZAZR CAFWV WAVUA HQIVG WVXPC KEWPC UZRIZ ZRCYU RAELX XCSLI PCZRC SIEUC
      UORWS RWQFC LZRCQ ZAZRC UCFIP IZWAV OCRAL XZRCU CZPEZ RUZAN CUCLH CJWXC VZZRI ZILLQ CVIPC SPCIZ CXCKE ILZRI ZZRCY IPCCV
      XAOCX NYZRC WPSPC IZAPO WZRSC PZIWV EVILW CVINL CPWMR ZUZRI ZIQAV MZRCU CIPCL WHCLW NCPZY IVXZR CFEPU EWZAH RIFFW VCUUZ
      RIZZA UCSEP CZRCU CPWMR ZUMAJ CPVQC VZUIP CWVUZ WZEZC XIQAV MQCVX CPWJW VMZRC WPBEU ZFAOC PUHPA QZRCS AVUCV ZAHZR CMAJC
      PVCX`
  },
  {
    id: 'substitution',
    type: 'substitution',
    params: { keyword: 'LIBERTY' },
    ciphertext: `VARJC JQARB KSOPR KTASH LJRUR JQPCQ IRBKH RPJRB RPPLO XTKOK JRMRK MGRQK ECPPK GURQA RMKGC QCBLG ILJEP VACBA ALURB KJJRB
      QREQA RHVCQ ALJKQ AROLJ EQKLP PSHRL HKJYQ ARMKV ROPKT QARRL OQAQA RPRML OLQRL JERNS LGPQL QCKJQ KVACB AQARG LVPKT JLQSO
      RLJEK TJLQS ORPYK ERJQC QGRQA RHLER BRJQO RPMRB QQKQA RKMCJ CKJPK THLJF CJEOR NSCOR PQALQ QARXP AKSGE ERBGL ORQAR BLSPR
      PVACB ACHMR GQARH QKQAR PRMLO LQCKJ VRAKG EQARP RQOSQ APQKI RPRGT RUCER JQQAL QLGGH RJLOR BORLQ RERNS LGQAL QQARX LORRJ
      EKVRE IXQAR COBOR LQKOV CQABR OQLCJ SJLGC RJLIG ROCYA QPQAL QLHKJ YQARP RLORG CTRGC IROQX LJEQA RMSOP SCQKT ALMMC JRPPQ
      ALQQK PRBSO RQARP ROCYA QPYKU ROJHR JQPLO RCJPQ CQSQR ELHKJ YHRJE ROCUC JYQAR CODSP QMKVR OPTOK HQARB KJPRJ QKTQA RYKUR
      OJRE`
  },
  {
    id: 'vigenere',
    type: 'vigenere',
    params: { keyword: 'INDEPENDENCE' },
    ciphertext: `EUHRX RGKIP QYZFH SULHP EAGZM AWWXX OHGBO IAAHG TWFDV LHSZB QIEIB SPRVS LVVWD PIHXU GTWYL XXGNO FNPHA JKMRL UDZRE SVAHG
      IIQWL ROAQG KECSG KIECR LGREH WHPIN OSVTW LTTBZ IEUSN GKITE EWLGJ IARSE GEGHE AFIYH DPHXN WMBPX WJKMR LGKIY CAABI RPXHU
      INPHW SQEIY EHWTQ HMAWM IPRWL ROELR FICXE HWCGG BGRXW IBSMA KSVFR JBEAN MAFVM DXMGI FWLNV XPRBW WSHOH QGGTN UIILR FEHUI
      AJKMR LVPTR NXPRP XDXUH WRREZ NWMDR JHLBN HBUHW TXEXX UUXWO HWTPS HZVFI VGWLP XNOPZ GRIEH GGINW IQGUC NOXWE GWLRA EZRHR
      SSJHH OAXPR LVRVR DXBTA QGKGT VGDMA WRIYL ICEOO IEKKP GVXWE GDQBP KBUHW TEEHP VHITV EIGXL DRQVL MCXVH YVWSS JEXCL RTWFW
      LNVXW FHGJV RWLRU IZVJL IWTRZ RTRUR QXHEE HMAUX QGXXT HNPSA IQMAG IGMIL RTVLM VUNJW GSSJG VASUS BXUHG BPWMA WSUXU HKBXI
      ZAHH`
  },
  {
    id: 'vigenereShort',
    type: 'vigenere',
    params: { keyword: 'EAGLE' },
    ciphertext: `AHKYM RTNPG SUXDI SFNFQ ENKGI RTYTX FEIZQ ISTPG ISYLV CFUCS REVPS TLKES HIYDS PVKEL IPUWM XIILP FATOW AHONL LABPG SNTPG
      XEJEL IMCTX LATZX LEXLR HTULW WUSPE QOTRX LEVZA IRYZJ XHKPE VTNEL ISKAE VAZPE RDKBY ELYEE XIUYX SWNTG LTNPP EWYZJ RAZFV
      IATOS JNGEY VEYRS HETEM XLKEL IMGOI GETEV ISVPG XTUEL IOVTR MOTDS JMGYO MNJCI UUOCI WTNLX XHKJW LOAWH HEIWE VEZSI GAADI
      WWNTG LISAI PTNPQ XOZSI WEVLV ETOZR AENZP HTNPW ITXFX LSZZF ISKWJ IVOOI RTZSE XARWQ INGCI GRKLX IDKBY ELZSE XTNPC ERKPR
      HOCPH FYZSI MRICI ETUCA MTNNI VTGTR YNGWM INGMP IRORL XSZSE XASZR KTNPW IAXPP MFKWM FEXEC ENJEL IPACW YIZZJ LAVAM REYDX
      LAZES WEIFV ITNPW IRORL XSMZZ IRTXI RTYLV IITDX MTAEI HASZR KMKYH IROGM RGZSI MRPFW XPUHI VSLCS QTNPG SNYPR XOLEL IGUGI
      VNKO`
  },
  {
    id: 'autokey',
    type: 'autokey',
    params: { primer: 'FREEDOM' },
    ciphertext: `BYIRL BFDLG BCELL SHVOD SRSAL HFSVX WIPHE MLOIE SEWSE CHSJG NVNJC GZRXD HWHDS EJHBZ WDZGM MPGPZ MIGLU WSJCU KSRLK QUUEX
      XGRGU IOPMW AHRAP PXYAA RMVEJ SHPXO MGFAF LEBCJ KKZSU HDIVS FYAAL ISVIH KHXWE CDVQN ELFWE JCOYL HWAQQ UMVAS IYZHM RLTQJ
      SFADH ZEETH USXTO WYEXA ZZHXU XUTOI VLRFR HWRIP MKSLW IQIBB BVRGD NZIBX ABIDE DEQEH JXXUB KLWRZ HHNSH BWJZU CHWLG NALWX
      ZAJIW ZMELL TVOMY ISEAL WQIOK HXASC WVHHT RGDIZ SEUNA LKXHS YLLDY SWMVI YYXCI WEYEF LNTRP NDINT VHGHY AEXKE JNHPR HRXXU
      HMWVH FLWVA MUDPX HXWIY ZXHVS IPIBU WRREI MAUOL PZMTH UDXYI ZHFGG NTAEE SNXXS MXILZ FPZYC LVEXY XNUEV NPXDZ YSJXB BJZSI
      WIGXG KXJUK XHZIU YIMZO XKKFD KYGEK BOWRE QMALL IKYBR VTUHH ZQHNP SEOHM AJXYM DZWAL ATWNN LKYGC IXYWH FBEXU XQTGZ ITHJJ
      KUIJ`
  },
  {
    id: 'beaufort',
    type: 'vigenere',
    params: { keyword: 'JEFFERSON' },
    ciphertext: `NXBSW EZHJH QLOMN EJGPS FSAWO BURWM EAPEC JRRBD AZAOW LZROQ EOZJV PUBLD PGVRQ UKAYL KYVTX MWPSD MJRCN IKKMG CEKBC DFBJH
      LBCLK OCRBL YFRDZ HJSES CLDSW VPSBF SDFIU CAQRI NBWZE LYBAR BVGQX BNACS XNQAF SBNCU NYMMF LJEBU VIYXC KZHJY EJNQM FOUPN
      BFROE JAJLL OAZMA KFRMX LGOVG FSFCA POBUS ANQAP ZVZQX BRPJF GZWMR ASRFE FWBOB OXKXJ RLYFL YLKPR XRLTO PKLYE OBLKO MNPMB
      NIKKM GBSQB TYLKB QQMYA ZOZNS EMXQE WKGVT CMXNA KUSKM YMYEN JRAUA AWKLJ WLMYE YSDCX ASFNN QXJJL BCABY OCQXF MLKOQ NSABS
      BDWKK IGMYA JBMWF EMRNV KVGHA OMEJF UAJTX BRRRD JSWZY LZZHN QETRR LZHJR AFOAG KJJYW EBNYU OAGLY BPXBW TBLRA XRDZF WANNL
      KSVUV MBDKA OVGFM BOWLL VVDQK BNEGK AQMFO AJFWU BLLMA OSCZW YTBRO OXFOW SZLKO GWAKN MPDWK WRZOR SYLKL VRNBR YEJUC AZRJN
      BBJG`
  },
  {
    id: 'playfair',
    type: 'playfair',
    params: { keyword: 'MONARCHY' },
    ciphertext: `VYGMG APDLE MVATF MPFMC RAFUG MLTKS CIHMC LQALE ILXBN DPHMN MGLFH VULPR BKXAP APUKL CFVHS ESKBM SCRAB TVYEB BVBOU FHMAW
      MGDLK CPDLC XGPDR ARPCF MRRYP RBXLX CLRON AKQCF VHUGA THPPD IUIMD ZDPCF LISOM RLKRA CKLWM STLRS FARQN VBFHY PDLUN XPAGO
      RSZMI MRYHP ARLZM KQIRH GMSKL PKLCF ORCKE LRQMK TQLES ZPRPD FMSFA GNAPA EORAE KRYMK LWKAI LPDRS PDGCP BMVTC CKEUR MKLCF
      BMXLI LVYEB BFOLL UPDLC PRPDI LFLRM RSFAY NFCMP KZCFL IZDZL BPPRC ILIPE FUKBG MSZPD RSMSU CGMRM LEMKR SKCGL XMPLB OSZPD
      GCRMI UGMHR UGCDD QCFKA DMIMP RNZKS YHKMS RGAWM MSKFA RCSKM KIDPT LBOSR ONYQP DILIM MKSEG FSECI DZBNR YPDFL ZMLXK SHPBO
      SVSFM GXATL BOSZP RLIEM MKPDI LKMKI DPQIH OKMAO GMLTR MFKAQ SKLZL KBRON YQCLR YKMFX GAKQC FKAEX TLVHU GATKO NOPDL ENALI
      RQHPP DFIHO KMMGB Z`
  },
  {
    id: 'bifid',
    type: 'bifid',
    params: { keyword: 'CONSTITUTION' },
    ciphertext: `XEINE OLEGB IKECI ACPCE EOREL NPSPC UCSXN HSIIB UOTFN FXCCE NIGRI FCNHI IOCBF LNNHT HCEGF LEGNM MNIAM BCIIC TFNNH DCEIB
      FONOO PNOEO SEGMA NCPSE CCGSI ICNMN IBHUP CFCGV EBUEM PNEUN TFNBP LGLCG NMMOC XEMNE EMNCO EHGWA CNIBQ EBEPI FHULF CGWPE
      IXUVG BSFCR IEHOI IBAOB HAECF OLNNE FPMGM ALWON HBOIN FQIEC FCCEB EGNMG CEXLP COPIC IIFBC HEAMW NNFMI STHNL LGCCE CEGEX
      LFBNN YCUYO BUGCN YTLOI PCSPY UWEEA CWVQI CYNIT CEPKM LSPCO GCVZL UTPFY TGZAQ UNUGY NUTMD LNZRL LGXVG VMERK OKULS YCFMA
      KDNKU GWVPD NVVTL AVCKV PCZDL ANOHU AKNZS IVRPZ LQMIZ CNVYC FLMLS OETLD DLLGX VAIMT YSTWY RBSCI CVKYK EONKC VKTSA TPZLP
      VNWIY RLTTN WWTLT XNAEC GLTNR RPXUG YSNVC ICLZP KYNDM TUPGN SRPZB CDTLL VHYFC XIKPV NRTDT FAFNV VCGYC VBXUT MWDLO HNWDL
      FCXT`
  },
  {
    id: 'railfence',
    type: 'transposition',
    params: { rails: 3 },
    ciphertext: `WIERF AEICS ERRPL DOTOI BSCVN THINE DSENE EFEHS RAQSI OCESA EOTSE THDNS THINM IERHH HDLTA SCPHO SROHT ETOEV NALAR EUHHR
      DDHCT IEIAN EHHMT ELLRN ESOPE HOUHR TVMSI IEOER NEUOS MCEFG RHNNH CUSOH MNVNS TEOEN CSAYO OEEPE OISLE HPLTC LADWI HAEON
      CETEW TAOHR NTASM AOGHP WROTE ATTEE AAENE ULTTO TWIHH LWONT RADFA UEGDN ILTEA EETEP CTTEP NOSFA KNRQI ETATE SOLDC AEHCU
      EWIHM ETETT EEAAI NEODH STUHT BSLEI ETHTL MNRCE TDQAT ATEAE NOEBT ERRAO WTCRA NNLEA LRGTT AAOGH SAEIE IETAD HPRUT FAPNS
      TATSC RTEEI HSOEN ETAEN TTTDM NMNEI IGHIJ SPWRF OTEOS NOTEO ENDET OEUET BMESF NOTSV EIANH HCEDM HTAOU MTOSH RHPTD AANHT
      AFUNN ROTEM CREOO IONDU STYUE RESHI LMHPT WLERS EFDTA EEAEL TYEWY IERHT UIBIS TNERF BYTUI HISTE ESGGR NRSUA GDVTR TERHN
      THVE`
  },
  {
    id: 'columnar',
    type: 'transposition',
    params: { keyword: 'ZEBRAS' },
    ciphertext: `IOFEI MEFPT OEINC CTMNA SMESE HRDSN CAANT OTMNE HIMDR THETS CLOPO LESED AEREH YDYCR EUNIH NEFRT SHETU STRSS EGRTU EMNFV
      EEEAT CERNL STIBH VEHHE OETEH HPAAI HEFEN STHCS OIOIU HYDRA HPMST HETEV TLEEL HEDIT HIIES MELBN UOIHE HGVNI UODNR ORCTG
      EHHSM NENAO PIELL WANTT HTMGW TTEEU TWHOR FENTE ETPSK QTELA CWMEE AEHUB ETLRT ATEEE ATALL TAHEI APTPT STIOE ETMNI IPFEN
      ENNCO NSOCY EESHT AIECE ARAAH RETAN LOILN AAGIE EPTNF NIASD EUIET EIOSH SIHMC DTENB ROCNE RTOSI EDRFN ACEHE TNTNE GJWOO
      OODNU HVTES OEOLP CDHOE WONSO POAEA ETTHW TDUDL ATCEO ARETO CHEHT TANDT TLETN EQAAO TRWRN AGAGA ETHUA STRES NATDM IHSRT
      STEWT RUEBS SRODV OASHN DITDU NOFRS TQAOT SUORE EDRTO NNESH ULESI HHRWT ROFNA AAUTR WHEIT ABHTT RLYEI PSOER GMRIA EVETS
      HEHR`
  },
  {
    id: 'adfgvx',
    type: 'adfgvx',
    params: { square: 'INDEPC176ABFGHJKLMOQRSTUVWXYZ0234589', keyword: 'LIBERTY' },
    ciphertext: `FAAXG XADGX GXDXA GAFGG AADGV XVAAF FVGGA GFXGV GXAVA VGDGG AVAVD AGGGG AAGVA FAGAA GDGXA FAGGG GFFGA GFDAD GGDVV AFGGV
      GXAVG VDXGG FGAFA GGAAA GGADA VAVDX GGAXD VAGGV DAGGG XFGFA GGDAA VFAAA FGGVG FFAAX FGADA GGAFG GVGGA GGDGG AAGVG GADFA
      AXGXF AGFGX GVGFG GFGDV AXGAG AFGDV DAGGA VAGAD GXGAA GDAAA GVVAA VGXAD AGAAG GADFD GVGGA FGVFG GVGVG GAFAV GGGVG ADGFA
      GGGVA GAVVF AGGGA GGGGD GDGFA GAAAX FFVAA XGFGD ADGAG FDADG GGDAA AGAGD AAVAG AGAXD GAGGG AGGDA DDXFA AGDGG DAGAD GVGDG
      VGGAF DFGDF DAGAG GGADF GGXGG ADAXA GGDFV FVAVG DGVAX GGDAG GFDAG AGDDG DAGAF GAAGA ADFGD FAGFD AGDAF GDAGD AGVAA FGAGA
      VGGFD ADAFA GGVGG DGAGV DFAAD AGAGA GGGGV FAGAA VAVGA DXAGA AADAA GGFGA AAFFG DGGVG DFDFG DFADG AAVFG AFAVA AAXFF GGDDF
      VAFAX VXAVG DAGAD GGGGA VADDV AGDFD DFGAD VGGVA XDXAG GDFGF GGAAF ADGAF VGDGX GGFGA XGGGX DDAFA DFVAX GXAAA AAADA FDXVV
      DAAGG AAAGA FVGVF DFDAD GVVDG FGGAA FAGVD DGGAF DVGAA DVXGG DVGFA GFGGG GVAAG GAGGV GGGFD VDGAA FGGGG AAVAV FAAGA VDXGF
      ADGVV GGFFF DFFFA GAVFG GAFGF GAGGV GAADG VAFAF GAADG DGGGX AAGAG AGAAD GVGFG GXGXD AGVFD GFGGA VGVFA AVADF GAVFD DVDVG
      GADVG FGGGG GAGDA VXADA XAXGG AAGXA VAVFV GAADG FFVGX AGFGG AFVFV AFGGA GGDDG VGFGA FAGGV GGAAD DAGVD GDFDA AGVAD DVFGD
      VGXDV AVGGA GAVVD GFGVA AAGAV GGVGF GGVFA AAVGG FGAGA XAGVF AVGGV DFADF ADADA DAGFG GGDDA DGDGV AFDGF GADFG GDGDA XFGGV
      DXGVG DAADD ADADF GFGGD GGAXG XFGDA FFGFG VFAAD FGAGA XFVDG VVAXG DAVGV DGFVD DAGAV GGFXA XAGFV AGGAG AFVAG GFAGG AFFGD
      DXAGG DVD`
  },
  {
    id: 'polybius',
    type: 'polybius',
    params: {},
    ciphertext: `52 23 15 33 24 33 44 23 15 13 34 45 42 43 15 34 21 23 45 32 11 33 15 51 15 33 44 43 24 44 12 15 13 34 32 15 43 33 15 13
      15 43 43 11 42 54 21 34 42 34 33 15 35 15 34 35 31 15 44 34 14 24 43 43 34 31 51 15 44 23 15 35 34 31 24 44 24 13 11 31
      12 11 33 14 43 52 23 24 13 23 23 11 51 15 13 34 33 33 15 13 44 15 14 44 23 15 32 52 24 44 23 11 33 34 44 23 15 42 11 33
      14 44 34 11 43 43 45 32 15 11 32 34 33 22 44 23 15 35 34 52 15 42 43 34 21 44 23 15 15 11 42 44 23 44 23 15 43 15 35 11
      42 11 44 15 11 33 14 15 41 45 11 31 43 44 11 44 24 34 33 44 34 52 23 24 13 23 44 23 15 31 11 52 43 34 21 33 11 44 45 42
      15 11 33 14 34 21 33 11 44 45 42 15 43 22 34 14 15 33 44 24 44 31 15 44 23 15 32 11 14 15 13 15 33 44 42 15 43 35 15 13
      44 44 34 44 23 15 34 35 24 33 24 34 33 43 34 21 32 11 33 25 24 33 14 42 15 41 45 24 42 15 43 44 23 11 44 44 23 15 54 43
      23 34 45 31 14 14 15 13 31 11 42 15 44 23 15 13 11 45 43 15 43 52 23 24 13 23 24 32 35 15 31 44 23 15 32 44 34 44 23 15
      43 15 35 11 42 11 44 24 34 33 52 15 23 34 31 14 44 23 15 43 15 44 42 45 44 23 43 44 34 12 15 43 15 31 21 15 51 24 14 15
      33 44 44 23 11 44 11 31 31 32 15 33 11 42 15 13 42 15 11 44 15 14 15 41 45 11 31 44 23 11 44 44 23 15 54 11 42 15 15 33
      14 34 52 15 14 12 54 44 23 15 24 42 13 42 15 11 44 34 42 52 24 44 23 13 15 42 44 11 24 33 45 33 11 31 24 15 33 11 12 31
      15 42 24 22 23 44 43 44 23 11 44 11 32 34 33 22 44 23 15 43 15 11 42 15 31 24 21 15 31 24 12 15 42 44 54 11 33 14 44 23
      15 35 45 42 43 45 24 44 34 21 23 11 35 35 24 33 15 43 43 44 23 11 44 44 34 43 15 13 45 42 15 44 23 15 43 15 42 24 22 23
      44 43 22 34 51 15 42 33 32 15 33 44 43 11 42 15 24 33 43 44 24 44 45 44 15 14 11 32 34 33 22 32 15 33 14 15 42 24 51 24
      33 22 44 23 15 24 42 24 45 43 44 35 34 52 15 42 43 21 42 34 32 44 23 15 13 34 33 43 15 33 44 34 21 44 23 15 22 34 51 15
      42 33 15 14`
  },
  {
    id: 'hill',
    type: 'hill',
    params: { matrix: '3 3 / 2 5' },
    ciphertext: `JBZVL DAVSS YYBUC AKTSW NNXJZ VHYDH PWWWW SPXSS OUCKT YFCPA ZUFYJ ZTQVE HUEWX FXKAV FFXFD HEAHD DCWPQ QTCBN VOXKW WANSS
      RGOXH IYEDH VODSA VLPNN OXQCE WSWMI AQFEA VFFEI LPSCU BHIMI EZAFH IOETE ZIRGN NVAEC HDHBF ROISR EITCB NAVTL OGSCC XFRHV
      MIWPF BNANI LCUOZ RZVDA MPRZH IKYVA SYSRL CVHSS KDVTH IJZLD OIPMF BKYRY LDINI KGCLC HBVOK DHIWI LGPRS VSSHW LCAVS SIWOE
      QQTCB NIYFY MNHIP PVTHI OETEZ IDADP AMLGQ LAVOU RZHEA VHBTH OUTLB EJEVA SRAVF RHDRE ZVZHS SLCFR VXIKI OMNVO KDHIU WLCZV
      ZYAMM LZNHI XXFLM IVENO DHBYL PFMLD VBHDK KNAKF LPQUA FHBVO FMAQF EAVOU MILCF KBEFK PWEZU WWPAV FFHVK GDHFB VOMBL DOUHB
      VOKDS OSSHV RZHIO EXWNV HYIEX KMVWS SRCKL CLDHB DHNFV XKIDP CUZVV AXWJE FEAVK WABKA YJEIL PRJPA PPHIW WPMZV VEUBH IIEXK
      MVVX`
  },
  {
    id: 'trapHill3',
    type: 'trap',
    expect: 'vigenere',
    params: { matrix: '6 24 1 / 13 16 10 / 20 17 15' },
    ciphertext: `SWVXL TAJNE IGSDE DUCSK GNBTR IOHGB ATOMY YIORW KOVOR SMVJD TYUFN MYACP UJYNW JHHTX TRSWP WFAFE UDEGT GHZYN LPNIQ MEBVE
      GHNXU WWQRK QOKPA JNLNP UPVIA EWYOQ UYHNX XTRSC MCZYZ XIQMS TXOAJ NLGDS MDCZG YXHEI KXXFW UBZIG VGFZY NAJNK ZEHOX TVZMA
      VDEGJ COIKZ IXCLU NRIOV YYTKO AKYMT CRIOI XCGTI MPDAJ NKIFY VIEZW GXSOT ELXUM OCSAP ZKIHA KGFWE SNXYI MTCFB HTKOU GKKQM
      TGHZY NNERV CGUPY BLTAX KUGXR VBHQV BEPNY SAJNP ULDDD ZXDIE THSVR BPUKL HNKJV JPAOZ MJWAL IAZSG TADEB GTWVF FXCCU UUNAI
      TBXQH DPLQB QLHFR IBUYP RKQVA ZSPGZ VPMWV YAPOV HOTUW DFWVF WDOMI TAJNW MMBFB QQTZV HJUEB AZNXU OYLIH KYCRQ VLQVZ KXAZK
      IHAKA QWPWL TKOSQ EOTUW DFDSX DMSZM JAPKY BIJXT EKDFD ZQUYA VWBEI YOVTL XFKCZ MDGTK UDNLA JLQYB SPKTE YYRRI OPKAO HMUMV
      CBXVN Q`
  },
  {
    id: 'trapShortVigenere',
    type: 'trap',
    expect: 'bifid',
    params: { keyword: 'LIBERTY' },
    ciphertext: `HPFRZ GRSMD SLKQP WGLLF YYMWI EMQTB`
  }
];
